# Generated by Django 4.2.6 on 2023-10-10 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_category_alter_myuser_user_type_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='last_price_update_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
