# Generated by Django 4.2.6 on 2023-10-11 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='failed_login_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
